version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: nelon_postgres
    restart: always
    environment:
      POSTGRES_DB: nelon_shift
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nelon_net

  backend:
    build: .
    container_name: nelon_shift_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nelon_shift
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    networks:
      - nelon_net

volumes:
  postgres_data:

networks:
  nelon_net:
